### ISSUE TITLE
JS v3.0 API Parsing/displaying of complex MultiPolygon shapes using KML/GeoJSON with "holes"

### ISSUE THREAD

**Issue by jesse-vericatch** [heremaps/maps-api-for-javascript-examples#64]
Hi there,

I've opened a support request relating to this same issue hoping that I'll get an answer back quickly relating to Heremaps JS API parsing of KML/GeoJSON MultiPolygons with "holes" in them as in the image below.

<img width="173" alt="Screen Shot 2019-09-18 at 3 21 24 PM" src="https://user-images.githubusercontent.com/38438736/65191176-04778700-da28-11e9-9e12-eb02d6b378cd.png">

As I'm a paying customer I've confirmed within the TCS Examples with KML and have uploaded the same KML file but don't see any of the cutout areas.

<img width="316" alt="Screen Shot 2019-09-18 at 3 21 02 PM" src="https://user-images.githubusercontent.com/38438736/65191188-0a6d6800-da28-11e9-83b7-48c9aa4e1150.png">

So what's the current status for being able to work with complex shapes like this or how would I go about using these?

Let me know what else I could provide you to assist.

Cheers,
Jesse

**Comment by germanz** [comment]
@jesse-vericatch use the [H.data.geojson.Reader](https://developer.here.com/documentation/maps/api_reference/H.data.geojson.Reader.html). We introduced a **disableLegacyMode** flag in order to support the complex geometries (MultiGeometry, holes) and do not break the backward compatibility. So the code should look like this:

```
var reader = new H.data.geojson.Reader('/path/to/geojson/file.json', {disableLegacyMode: true});
reader.parse();
map.addLayer(reader.getLayer());
```
Please attach an example dataset if it still does not work.
Polygons with holes with the KML are not supported at the moment.

**Comment by Wokiri** [comment]
Hello,

I have a valid geojson file which does not render in my map. Instead, my console reports something of this nature...
Cannot GET /%7B%22type%22:%22FeatureCollection%22,%22name%22:%22CircularArea%22,%22crs%22:%7B%22type%22:%22name%22,%22properties%22:%7B%22name%22:%22urn:ogc:def:crs:OGC:1.3:CRS84%22%7D%7D,%22features%22:[%7B%22type%22:%22Feature%22,%22geometry%22:%7B%22type%22:%22Polygon%22,%22coordinates%22:[[[28.03751,-26.21245],[28.03777,-26.21245],[28.03803,-26.21245],[28.03829,-26.21247],[28.03855,-26.21248],[28.03881,-26.2125],[28.03907,-26.21253],[28.03933,-26.21256],[28.03959,-26.21259]....

This is just a section of the message. Would you help me figure out the reason for this anomaly, I guess it is on my side.

Thanks.

**Comment by ttobis** [comment]
@Wokiri can you please share reproducible code sample?

**Comment by Wokiri** [comment]
https://1drv.ms/u/s!AnbB9qGR0gszgYZ9kygwksmLMaCMiA?e=Ofbc2G

Kindly receive. I have not included my API key I hope you will append yours,
Thanks.

**Comment by ttobis** [comment]
ok, I see where the problem is.

As per the [geojson.Reader documentation](https://developer.here.com/documentation/maps/3.1.20.0/api_reference/H.data.geojson.Reader.html), the first parameter should be URL to geojson file, not the geojson data.
If you want to parse geojson data, then create instance of Reader with undefined first parameter: `geoJsonReader = new H.data.geojson.Reader(undefined, {...`
and then parse the data using `parseData` method, instead of `parse`:
 `geoJsonReader.parseData(data)`

**Comment by Wokiri** [comment]
Many thanks...

**Comment by oleksmarkh** [comment]
Polygons with holes are supported for KML since `v3.1.15.0`:

```js
function getKml(xml) {
  return `<?xml version="1.0" encoding="UTF-8"?>
    <kml xmlns="http://www.opengis.net/kml/2.2">
      ${xml}
    </kml>`.replace(/\n/g, '').replace(/>\s*</g, '><');
};

const polygonKml = getKml(`
  <Document>
    <Folder>
      <name>InputLayer</name>
      <Placemark>
        <MultiGeometry>
          <Polygon>
            <outerBoundaryIs>
              <LinearRing><coordinates>...</coordinates></LinearRing>
            </outerBoundaryIs>

            <innerBoundaryIs>
              <LinearRing><coordinates>...</coordinates></LinearRing>
            </innerBoundaryIs>

            <innerBoundaryIs>
              <LinearRing><coordinates>...</coordinates></LinearRing>
            </innerBoundaryIs>

            <innerBoundaryIs>
              <LinearRing><coordinates>...</coordinates></LinearRing>
            </innerBoundaryIs>
          </Polygon>
        </MultiGeometry>
      </Placemark>
    </Folder>
  </Document>
`);

const kmlReader = new H.data.kml.Reader(null);
kmlReader.setState(H.data.AbstractReader.State['LOADING']);
kmlReader.createObjects(polygonKml);
console.log(kmlReader.getLayer().getProvider().getRootGroup().getObjects());
map.addLayer(kmlReader.getLayer());
```
